### Bài toán có nhiều hơn 2 lớp phân loại

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = sns.load_dataset('iris')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

### Nhìn chung hồi quy logistics thì target là categorical variables

In [7]:
# chuyển biến species sang kiểu số
# sử dụng LabelEncoder --> tự làm (do biến output là categorical variable) 
# sử dụng dictionary để thay thế
dict_species = {'setosa': 0, 'versicolor': 1, 'virginica': 2}
# df['species_encode'] = [dict_species[i] for i in df['species']]
# df['species_encode'] = df['species'].map(lambda x: dict_species[x])
df['species_encode'] = df['species'].map(dict_species)

In [8]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species  \
0           5.1          3.5           1.4          0.2  setosa   
1           4.9          3.0           1.4          0.2  setosa   
2           4.7          3.2           1.3          0.2  setosa   
3           4.6          3.1           1.5          0.2  setosa   
4           5.0          3.6           1.4          0.2  setosa   

   species_encode  
0               0  
1               0  
2               0  
3               0  
4               0

In [9]:
df.tail()

sepal_length  sepal_width  petal_length  petal_width    species  \
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     species_encode  
145               2  
146               2  
147               2  
148               2  
149               2

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [17]:
X = df.drop(['species', 'species_encode'], axis=1) #predict
y = df['species_encode'] #target

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [18]:
#khởi tạo model
model = LogisticRegression(multi_class='multinomial') #multinomial là cho nhiều giá trị á (mặc định là 0 vs 1)

In [19]:
# huấn luyện model
model.fit(X_train, y_train)

LogisticRegression(multi_class='multinomial')

In [21]:
yhat_train = model.predict(X_train)

In [22]:
y_train[:5]

23     0
136    2
36     0
85     1
19     0
Name: species_encode, dtype: int64

In [23]:
yhat_train[:5]

array([0, 2, 0, 1, 0], dtype=int64)

In [24]:
yhat_test = model.predict(X_test)

In [25]:
y_test[:5]

134    2
90     1
33     0
120    2
51     1
Name: species_encode, dtype: int64

In [26]:
yhat_test[:5]

array([2, 1, 0, 2, 1], dtype=int64)

In [27]:
from sklearn.metrics import accuracy_score

In [30]:
print('Accuracy score in train:', accuracy_score(y_train, yhat_train))
print('Accuracy score in test:', accuracy_score(y_test, yhat_test))

Accuracy score in train: 0.9833333333333333
Accuracy score in test: 0.9666666666666667


In [31]:
#sepal_length	sepal_width	petal_length	petal_width
X_new = [[4.9, 3.3, 1.7, 0.4], [5.8, 3.9, 4.8, 2.0]]
yhat_new = model.predict(X_new)
yhat_new

C:\Users\trung\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0, 2], dtype=int64)

In [33]:
'''
=> [4.9, 3.3, 1.7, 0.4] :lớp 0
[5.8, 3.9, 4.8, 2.0]: lớp 2
'''

'\n=> [4.9, 3.3, 1.7, 0.4] :lớp 0\n[5.8, 3.9, 4.8, 2.0]: lớp 2\n'