In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('data/inaugural_speeches_clean.csv')

In [3]:
df[['text_clean', 'char_count', 'word_count', 'avg_word_length']].head()

text_clean  char_count  word_count  \
0  fellow citizens of the senate and of the house...        8503        1432   
1  fellow citizens i am again called upon by the ...         775         135   
2  when it was first perceived in early times tha...       13605        2323   
3  friends and fellow citizens called upon to und...        9931        1736   
4  proceeding fellow citizens to that qualificati...       12680        2169   

   avg_word_length  
0         5.937849  
1         5.740741  
2         5.856651  
3         5.720622  
4         5.846012

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
# khởi tạo countVectorizer
cv = CountVectorizer()

In [7]:
# phân rã nội dung văn bản
# cv.fit(df['text_clean'])
# df_transform = cv.transform(df['text_clean'])
df_transform = cv.fit_transform(df['text_clean'])

In [9]:
print(cv.get_feature_names())

['abandon', 'abandoned', 'abandonment', 'abate', 'abdicated', 'abeyance', 'abhorring', 'abide', 'abiding', 'abilities', 'ability', 'abject', 'able', 'ably', 'abnormal', 'abode', 'abolish', 'abolished', 'abolishing', 'aboriginal', 'aborigines', 'abound', 'abounding', 'abounds', 'about', 'above', 'abraham', 'abreast', 'abridging', 'abroad', 'absence', 'absent', 'absolute', 'absolutely', 'absolutism', 'absorb', 'absorbed', 'absorbing', 'absorbs', 'abstain', 'abstaining', 'abstract', 'abstractions', 'absurd', 'abundance', 'abundant', 'abundantly', 'abuse', 'abused', 'abuses', 'academies', 'accept', 'acceptance', 'accepted', 'accepting', 'accepts', 'access', 'accessible', 'accession', 'accident', 'accidental', 'accidents', 'acclaim', 'accommodation', 'accommodations', 'accompanied', 'accompany', 'accomplish', 'accomplished', 'accomplishing', 'accomplishment', 'accomplishments', 'accord', 'accordance', 'accorded', 'according', 'accordingly', 'accords', 'account', 'accountability', 'accountab

In [11]:
len(cv.get_feature_names())

9043

In [13]:
df_transform = df_transform.toarray()

In [14]:
df_transform

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
# chuyển về DataFrame
df_transform = pd.DataFrame(df_transform, columns = cv.get_feature_names()).add_prefix('counts_')
df_transform.head()

counts_abandon  counts_abandoned  counts_abandonment  counts_abate  \
0               0                 0                   0             0   
1               0                 0                   0             0   
2               0                 1                   0             0   
3               1                 0                   0             0   
4               0                 0                   0             0   

   counts_abdicated  counts_abeyance  counts_abhorring  counts_abide  \
0                 0                0                 0             0   
1                 0                0                 0             0   
2                 0                0                 0             0   
3                 0                0                 0             0   
4                 0                0                 0             0   

   counts_abiding  counts_abilities  ...  counts_your  counts_yours  \
0               0                 0  ...            9             0   
1               0                 0  ...            1             0   
2               0                 0  ...            1             0   
3               0                 0  ...            7             0   
4               0                 0  ...            4             0   

   counts_yourself  counts_yourselves  counts_youth  counts_youthful  \
0                0                  0             0                0   
1                0                  0             0                0   
2                0                  0             0                0   
3                0                  0             0                0   
4                0                  0             0                0   

   counts_zeal  counts_zealous  counts_zealously  counts_zone  
0            0               0                 0            0  
1            0               0                 0            0  
2            1               0                 0            0  
3            1               0                 0            0  
4            3               0                 0            0  

[5 rows x 9043 columns]

In [16]:
df_transform.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Columns: 9043 entries, counts_abandon to counts_zone
dtypes: int64(9043)
memory usage: 4.0 MB


In [18]:
df_new = pd.concat([df, df_transform], axis=1)
df_new.drop(['text','text_clean'], axis=1, inplace=True)
df_new.head()

Name         Inaugural Address                      Date  \
0  George Washington   First Inaugural Address  Thursday, April 30, 1789   
1  George Washington  Second Inaugural Address     Monday, March 4, 1793   
2         John Adams         Inaugural Address   Saturday, March 4, 1797   
3   Thomas Jefferson   First Inaugural Address  Wednesday, March 4, 1801   
4   Thomas Jefferson  Second Inaugural Address     Monday, March 4, 1805   

   char_count  word_count  avg_word_length  counts_abandon  counts_abandoned  \
0        8503        1432         5.937849               0                 0   
1         775         135         5.740741               0                 0   
2       13605        2323         5.856651               0                 1   
3        9931        1736         5.720622               1                 0   
4       12680        2169         5.846012               0                 0   

   counts_abandonment  counts_abate  ...  counts_your  counts_yours  \
0                   0             0  ...            9             0   
1                   0             0  ...            1             0   
2                   0             0  ...            1             0   
3                   0             0  ...            7             0   
4                   0             0  ...            4             0   

   counts_yourself  counts_yourselves  counts_youth  counts_youthful  \
0                0                  0             0                0   
1                0                  0             0                0   
2                0                  0             0                0   
3                0                  0             0                0   
4                0                  0             0                0   

   counts_zeal  counts_zealous  counts_zealously  counts_zone  
0            0               0                 0            0  
1            0               0                 0            0  
2            1               0                 0            0  
3            1               0                 0            0  
4            3               0                 0            0  

[5 rows x 9049 columns]

In [19]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Columns: 9049 entries, Name to counts_zone
dtypes: float64(1), int64(9045), object(3)
memory usage: 4.0+ MB


## Bổ sung min_df và max_df

In [20]:
cv2 = CountVectorizer(min_df=0.2, max_df=0.8)

In [21]:
df_transform2 =cv2.fit_transform(df['text_clean']).toarray()
df_transform2

array([[ 0,  0,  0, ...,  5,  0,  9],
       [ 0,  0,  0, ...,  0,  0,  1],
       [ 0,  0,  0, ...,  0,  0,  1],
       ...,
       [ 0,  1,  0, ..., 14,  1,  3],
       [ 0,  0,  0, ...,  5,  1,  0],
       [ 0,  0,  0, ..., 14,  1, 11]], dtype=int64)

In [23]:
print(len(cv2.get_feature_names()))

818


In [24]:
# chuyển về DataFrame
df_transform2 = pd.DataFrame(df_transform2, columns = cv2.get_feature_names()).add_prefix('counts_')
df_transform2.head()

counts_abiding  counts_ability  counts_able  counts_about  counts_above  \
0               0               0            0             0             0   
1               0               0            0             1             0   
2               0               0            0             0             0   
3               0               0            0             1             1   
4               0               0            1             0             0   

   counts_abroad  counts_accept  counts_accomplished  counts_achieve  \
0              0              0                    1               0   
1              0              0                    0               0   
2              1              0                    0               0   
3              1              0                    0               0   
4              0              0                    0               0   

   counts_across  ...  counts_women  counts_words  counts_work  counts_wrong  \
0              0  ...             0             0            0             0   
1              0  ...             0             0            0             0   
2              0  ...             0             0            0             0   
3              0  ...             0             0            1             2   
4              0  ...             0             0            0             0   

   counts_year  counts_years  counts_yet  counts_you  counts_young  \
0            0             1           0           5             0   
1            0             0           0           0             0   
2            2             3           0           0             0   
3            0             0           2           7             0   
4            2             2           2           4             0   

   counts_your  
0            9  
1            1  
2            1  
3            7  
4            4  

[5 rows x 818 columns]

In [25]:
df_new2 = pd.concat([df, df_transform2], axis=1)
df_new2.drop(['text','text_clean'], axis=1, inplace=True)
df_new2.head()

Name         Inaugural Address                      Date  \
0  George Washington   First Inaugural Address  Thursday, April 30, 1789   
1  George Washington  Second Inaugural Address     Monday, March 4, 1793   
2         John Adams         Inaugural Address   Saturday, March 4, 1797   
3   Thomas Jefferson   First Inaugural Address  Wednesday, March 4, 1801   
4   Thomas Jefferson  Second Inaugural Address     Monday, March 4, 1805   

   char_count  word_count  avg_word_length  counts_abiding  counts_ability  \
0        8503        1432         5.937849               0               0   
1         775         135         5.740741               0               0   
2       13605        2323         5.856651               0               0   
3        9931        1736         5.720622               0               0   
4       12680        2169         5.846012               0               0   

   counts_able  counts_about  ...  counts_women  counts_words  counts_work  \
0            0             0  ...             0             0            0   
1            0             1  ...             0             0            0   
2            0             0  ...             0             0            0   
3            0             1  ...             0             0            1   
4            1             0  ...             0             0            0   

   counts_wrong  counts_year  counts_years  counts_yet  counts_you  \
0             0            0             1           0           5   
1             0            0             0           0           0   
2             0            2             3           0           0   
3             2            0             0           2           7   
4             0            2             2           2           4   

   counts_young  counts_your  
0             0            9  
1             0            1  
2             0            1  
3             0            7  
4             0            4  

[5 rows x 824 columns]

In [26]:
df_new2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Columns: 824 entries, Name to counts_your
dtypes: float64(1), int64(820), object(3)
memory usage: 373.5+ KB


## sử dụng max_fetures và stop_word

In [28]:
cv3 = CountVectorizer(max_features=100, stop_words='english')

In [30]:
f = open('data/vietnamese-stopwords.txt', encoding='utf-8')
noidung = f.read()
vie_stopwords = noidung.split('\n')
print(vie_stopwords)

['a lô', 'a ha', 'ai', 'ai ai', 'ai nấy', 'ai đó', 'alô', 'amen', 'anh', 'anh ấy', 'ba', 'ba ba', 'ba bản', 'ba cùng', 'ba họ', 'ba ngày', 'ba ngôi', 'ba tăng', 'bao giờ', 'bao lâu', 'bao nhiêu', 'bao nả', 'bay biến', 'biết', 'biết bao', 'biết bao nhiêu', 'biết chắc', 'biết chừng nào', 'biết mình', 'biết mấy', 'biết thế', 'biết trước', 'biết việc', 'biết đâu', 'biết đâu chừng', 'biết đâu đấy', 'biết được', 'buổi', 'buổi làm', 'buổi mới', 'buổi ngày', 'buổi sớm', 'bà', 'bà ấy', 'bài', 'bài bác', 'bài bỏ', 'bài cái', 'bác', 'bán', 'bán cấp', 'bán dạ', 'bán thế', 'bây bẩy', 'bây chừ', 'bây giờ', 'bây nhiêu', 'bèn', 'béng', 'bên', 'bên bị', 'bên có', 'bên cạnh', 'bông', 'bước', 'bước khỏi', 'bước tới', 'bước đi', 'bạn', 'bản', 'bản bộ', 'bản riêng', 'bản thân', 'bản ý', 'bất chợt', 'bất cứ', 'bất giác', 'bất kì', 'bất kể', 'bất kỳ', 'bất luận', 'bất ngờ', 'bất nhược', 'bất quá', 'bất quá chỉ', 'bất thình lình', 'bất tử', 'bất đồ', 'bấy', 'bấy chầy', 'bấy chừ', 'bấy giờ', 'bấy lâu', 'bấy lâ

In [31]:
# cv4 = CountVectorizer(max_features=100, stop_words=vie_stopwords)

In [32]:
df_transform3 =cv3.fit_transform(df['text_clean']).toarray()
df_transform3

array([[ 0,  2,  0, ...,  0,  1,  1],
       [ 0,  1,  1, ...,  0,  0,  0],
       [ 0,  3,  5, ...,  0,  3,  3],
       ...,
       [ 1,  0, 10, ...,  6,  7,  1],
       [ 1,  0,  8, ...,  4,  3,  5],
       [ 2,  1, 20, ...,  1,  6,  2]], dtype=int64)

In [33]:
len(cv3.get_feature_names())

100

In [34]:
print(cv3.get_feature_names())

['action', 'administration', 'america', 'american', 'americans', 'believe', 'best', 'better', 'change', 'citizens', 'come', 'common', 'confidence', 'congress', 'constitution', 'country', 'day', 'duties', 'duty', 'equal', 'executive', 'faith', 'far', 'federal', 'fellow', 'force', 'foreign', 'free', 'freedom', 'future', 'general', 'god', 'good', 'government', 'great', 'high', 'history', 'home', 'hope', 'human', 'institutions', 'interests', 'just', 'justice', 'know', 'land', 'law', 'laws', 'let', 'liberty', 'life', 'long', 'make', 'man', 'means', 'men', 'nation', 'national', 'nations', 'necessary', 'need', 'new', 'office', 'old', 'order', 'party', 'peace', 'people', 'place', 'policy', 'political', 'power', 'powers', 'present', 'president', 'principles', 'progress', 'prosperity', 'public', 'purpose', 'right', 'rights', 'secure', 'service', 'shall', 'spirit', 'state', 'states', 'strength', 'support', 'things', 'time', 'today', 'union', 'united', 'war', 'way', 'work', 'world', 'years']


In [35]:
# chuyển về DataFrame
df_transform3 = pd.DataFrame(df_transform3, columns = cv3.get_feature_names()).add_prefix('counts_')
df_transform3.head()

counts_action  counts_administration  counts_america  counts_american  \
0              0                      2               0                2   
1              0                      1               1                0   
2              0                      3               5                3   
3              0                      2               0                0   
4              1                      1               0                1   

   counts_americans  counts_believe  counts_best  counts_better  \
0                 0               0            0              0   
1                 0               0            0              0   
2                 0               0            1              2   
3                 0               2            3              1   
4                 0               0            2              1   

   counts_change  counts_citizens  ...  counts_things  counts_time  \
0              0                5  ...              0            1   
1              0                1  ...              0            0   
2              0                5  ...              1            1   
3              1                7  ...              1            0   
4              2               10  ...              2            6   

   counts_today  counts_union  counts_united  counts_war  counts_way  \
0             0             2              4           0           1   
1             0             0              1           0           0   
2             0             2              3           1           0   
3             0             2              0           1           0   
4             0             3              1           3           0   

   counts_work  counts_world  counts_years  
0            0             1             1  
1            0             0             0  
2            0             3             3  
3            1             3             0  
4            0             2             2  

[5 rows x 100 columns]

In [37]:
df_transform3.iloc[0].sort_values(ascending=False)

counts_government    8
counts_public        6
counts_country       5
counts_citizens      5
counts_present       5
                    ..
counts_progress      0
counts_god           0
counts_general       0
counts_freedom       0
counts_action        0
Name: 0, Length: 100, dtype: int64

In [41]:
df_transform3.sum().sort_values(ascending=False)

counts_government    593
counts_people        567
counts_great         338
counts_world         337
counts_states        326
                    ... 
counts_action         69
counts_means          67
counts_secure         66
counts_change         66
counts_order          66
Length: 100, dtype: int64

## Sử dụng n-gram

In [38]:
cv4 = CountVectorizer(ngram_range=(2,2))

In [39]:
df_transform4 =cv4.fit_transform(df['text_clean']).toarray()
df_transform4

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [40]:
print(cv4.get_feature_names())

['abandon all', 'abandon government', 'abandon mastery', 'abandon our', 'abandon their', 'abandon these', 'abandon they', 'abandon yet', 'abandoned and', 'abandoned by', 'abandoned the', 'abandoned we', 'abandonment and', 'abandonment of', 'abate under', 'abdicated practices', 'abeyance the', 'abhorring war', 'abide by', 'abiding but', 'abiding citizen', 'abiding citizens', 'abiding confidence', 'abiding creed', 'abiding divisions', 'abiding faith', 'abiding foundations', 'abiding group', 'abiding no', 'abiding people', 'abiding realization', 'abiding respect', 'abilities and', 'abilities but', 'abilities communism', 'abilities in', 'abilities to', 'ability all', 'ability and', 'ability appoint', 'ability derive', 'ability in', 'ability of', 'ability our', 'ability preserve', 'ability returns', 'ability shall', 'ability the', 'ability to', 'abject dependence', 'able and', 'able cooperation', 'able counsel', 'able depositaries', 'able to', 'ably and', 'abnormal demands', 'abnormal expen